// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Z8dm6OYdK19E63QYryZrtLxkQc8vfXQ',
    appId: '1:1040008832715:web:c7001d42fa07f8e3499d4e',
    messagingSenderId: '1040008832715',
    projectId: 'jobspot-16',
    authDomain: 'jobspot-16.firebaseapp.com',
    storageBucket: 'jobspot-16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW8kfscG3qAzGOJaVW90u59WLwM35lDvM',
    appId: '1:1040008832715:android:0e4718399b4a3a7c499d4e',
    messagingSenderId: '1040008832715',
    projectId: 'jobspot-16',
    storageBucket: 'jobspot-16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtdmzN9L7xSn9CZaqHKuCGa-c6UfmbLEA',
    appId: '1:1040008832715:ios:e68ad44b677ca175499d4e',
    messagingSenderId: '1040008832715',
    projectId: 'jobspot-16',
    storageBucket: 'jobspot-16.appspot.com',
    iosClientId: '1040008832715-jtepohahj3ib6vran3lsepibshopkrmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobspot',
  );
}
